/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0f172a",
        "on-primary": "#ffffff",
        "primary-container": "#1e293b",
        "on-primary-container": "#f8fafc",
        "inverse-primary": "#bec6e0",
        "secondary": "#64748b",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2e8f0",
        "on-secondary-container": "#0f172a",
        "secondary-fixed": "#d5e3fd",
        "secondary-fixed-dim": "#b9c7e0",
        "on-secondary-fixed": "#0d1c2f",
        "on-secondary-fixed-variant": "#3a485c",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#271901",
        "on-tertiary-container": "#98805d",
        "tertiary-fixed": "#fcdeb5",
        "tertiary-fixed-dim": "#dec29a",
        "on-tertiary-fixed": "#271901",
        "on-tertiary-fixed-variant": "#574425",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f8fafc",
        "on-background": "#0f172a",
        "surface": "#ffffff",
        "on-surface": "#0f172a",
        "on-surface-variant": "#45464d",
        "surface-variant": "#e4e2e4",
        "surface-dim": "#dcd9db",
        "surface-bright": "#fcf8fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f5f9",
        "surface-container": "#f0edef",
        "surface-container-high": "#eae7e9",
        "surface-container-highest": "#e2e8f0",
        "surface-tint": "#565e74",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "inverse-surface": "#303032",
        "inverse-on-surface": "#f3f0f2",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        // Status colors
        "status-critical": "#ef4444",
        "status-critical-bg": "#fee2e2",
        "status-high": "#f97316",
        "status-high-bg": "#fff7ed",
        "status-medium": "#f59e0b",
        "status-medium-bg": "#fffbeb",
        "status-low": "#10b981",
        "status-low-bg": "#d1fae5",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "base": "4px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      fontFamily: {
        "sans": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        "level-1": "0 4px 6px -1px rgba(15, 23, 42, 0.05), 0 2px 4px -2px rgba(15, 23, 42, 0.05)",
        "level-2": "0 10px 15px -3px rgba(15, 23, 42, 0.08), 0 4px 6px -4px rgba(15, 23, 42, 0.05)",
      },
      maxWidth: {
        "container": "1280px",
      },
    },
  },
  plugins: [],
}
